name: Deploy NetBox Configurations

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Debug SSH secrets
      run: |
        echo "Host: ${{ secrets.SSH_HOST }}"
        echo "User: ${{ secrets.SSH_USER }}"
        echo "Port: ${{ secrets.SSH_PORT }}"
        echo "Key exists: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
    
  sync-netbox:
    name: Run NetBox Sync Script Remotely
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Run NetBox Sync Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /ścieżka/do/skryptu
            python3 netbox_sync.py

  ansible-deploy:
    name: Ansible Backup & Deploy
    needs: sync-netbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook (Backup & Deploy)
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i hosts.ini playbooks/deploy_and_backup.yml --private-key ~/.ssh/id_rsa -u ${{ secrets.SSH_USER }}

  manual-approval:
    name: Manual Approval for Rollback
    needs: ansible-deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      # wymusi ręczną akceptację w GitHub UI przed przejściem dalej
      # (wymaga skonfigurowania środowiska "production" z reviewerami)
    steps:
      - name: Wait for admin approval
        run: echo "Czekam na ręczną akceptację lub odrzucenie rollbacku..."

  ansible-rollback:
    name: Ansible Rollback (optional)
    needs: manual-approval
    if: ${{ github.ref == 'refs/heads/main' && github.environment == 'production' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH for Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook (Rollback)
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook -i hosts.ini playbooks/rollback.yml --private-key ~/.ssh/id_rsa -u ${{ secrets.SSH_USER }}
